### ISSUE TITLE
Code example styling does not match

### ISSUE THREAD

**Issue by huayunh** [pxblue/multiselect-list#39]
#### Describe the desired behavior

list item style needs to match
header style needs to match

React:
![image](https://user-images.githubusercontent.com/8997218/71998318-63e2e800-320d-11ea-9053-493ede57d9a2.png)

Ionic:
![image](https://user-images.githubusercontent.com/8997218/71998361-72310400-320d-11ea-8186-84431f1bf8fe.png)

#### Describe the current behavior
![image](https://user-images.githubusercontent.com/8997218/71998233-444bbf80-320d-11ea-9e98-1f5075384c49.png)
Angular

#### Is this request related to a current issue?
No

**Comment by daileytj** [comment]
Closing this issue as it was resolved in the design pattern migration. We will need to keep an eye out when doing the Ionic and RN migrations to make sure the styling matches the current Angular/React examples.
