### ISSUE TITLE
Headers does not match each other in the styling

### ISSUE THREAD

**Issue by emclaug2** [pxblue/multiselect-list#40]
#### Describe the bug
The `<Header />` component renders differently across different branches.

#### What is the expected behavior?
Their title should all be left-aligned and bolded, and the application bar should have the same height for different sized view port unless specified otherwise.

#### What are the steps to reproduce?
1. goto our multiselect-list and status-list repo
2. open the code examples in online editors
3. compare the rendered result for each branch side-by-side

#### Screenshots or links to minimum reproduction example
multiselect-list
![image](https://user-images.githubusercontent.com/8997218/72071767-90a10900-32ba-11ea-9b85-e5b815d75977.png)

Status-list
![image](https://user-images.githubusercontent.com/8997218/72071932-e5448400-32ba-11ea-9096-7311761d0b16.png)

#### What is your environment?

 Framework
- [x] Angular
- [x] React
- [x] React Native

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari
- [x] Chrome
- [ ] Firefox

 Operating System
- [x] MacOS
- [ ] Windows
- [ ] Other

**Comment by daileytj** [comment]
Closing this issue as it was resolved in the design pattern migration. We will need to keep an eye out when doing the Ionic and RN migrations to make sure the styling matches the current Angular/React examples.
